name: Test MacOS

on:
  # push:
  #   branches:
  #     - '**'
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Testing ${{matrix.os}} py-${{matrix.python-version}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: ['macos-latest']
        python-version: ['3.14']

    env:
      HOMEBREW_NO_AUTO_UPDATE: "1"

    steps:
      - uses: actions/checkout@v6

      - name: Install Homebrew dependencies
        run: |
          brew install libomp llvm gcc
          which gfortran-14

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Build & install (macOS only)
        run: |
          uv sync --dev --all-extras
          # These are missed from the build-system for some reason?
          uv pip install scikit-build-core pybind11
          uv pip install -e .[test] --verbose

      - name: Run pytest
        run: uv run pytest tests/ -v -s

